name: taif
description: "مُحرر لغة ألف"
version: 1.0.0+1

environment:
    sdk: ">=3.10.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    lucide_icons_flutter: ^3.1.9
    file_saver: ^0.3.1
    shared_preferences: ^2.5.4
    path_provider: ^2.1.5
    permission_handler: ^12.0.1
    code_forge: ^8.1.0
    url_launcher: ^6.3.2
    input_quantity: ^2.5.2
    provider: ^6.1.5+1
    package_info_plus: ^9.0.0
    ota_update: ^7.1.0

    flutter_localizations:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/
        - assets/aliflang/
        - assets/aliflang/arm64-v8a/libalif.so
        - assets/aliflang/arm64-v8a/libc++_shared.so
        - assets/aliflang/library/
        - assets/aliflang/linux/amd64

    fonts:
        - family: Tajawal
          fonts:
              - asset: assets/Tajawal.ttf

flutter_intl:
    enabled: true
